### ISSUE TITLE
[Bug]: GPUMultisampleState.EnableAlphaToCoverage is private with no public property

### ISSUE THREAD

**Issue by kraybit** [edwardgushchin/SDL3-CS#303]
### Prerequisites

- [x] I searched the existing issues and did not find a duplicate.
- [x] This is not a security vulnerability. I will use the private reporting process for security issues.

### Area

Render or GPU

### SDL3-CS version

3.4.16.0

### Environment

OS: Windows 11 x64 (10.0.26200)
.NET SDK/runtime: SDK 10.0.401, runtime 10.0.12
Target framework: net10.0
RID: win-x64
Packages: SDL3-CS 3.4.16, SDL3-CS.Windows 3.4.16 (both built from commit c1d1cb0, tag v3.4.16.0)
GPU backends tried: D3D12 and Vulkan (SDL_GPU)

### Problem description

- `SDL_GPUMultisampleState.enable_alpha_to_coverage` cannot be set from C#.

- `GPUMultisampleState.EnableAlphaToCoverage` is declared `private byte` with no public bool property (`SDL3-CS/SDL/GPU/gpu/GPUMultisampleState.cs`)

### Minimal reproduction

```csharp
var multisample = new SDL.GPUMultisampleState
{
    SampleCount = SDL.GPUSampleCount.SampleCount8,
    EnableAlphaToCoverage = true,   // error CS0122: inaccessible due to its protection level
};
```

### Expected behavior

The above code should not cause a compiler error, and work.

### Logs or error output

```shell

```

### Additional context

Still present at tag v3.4.16.1.

### Code of Conduct

- [x] I agree to follow the project's Code of Conduct.

**Comment by edwardgushchin** [comment]
I reproduced the issue and am working on a fix for SDL3-CS 3.4.16.2.

**Comment by edwardgushchin** [comment]
A fix is available in PR #304: https://github.com/edwardgushchin/SDL3-CS/pull/304.

**Comment by edwardgushchin** [comment]
The fix from PR #304 has been merged and is ready for release in SDL3-CS 3.4.16.2.
